### ISSUE TITLE
EntrySys has a wrong availableLanguage type + use of 'any'

### ISSUE THREAD

**Issue by opgbaudouin** [contensis/contensis-core-api#3]
In /src/models/EntrySys.ts the field availableLanguage should be availableLanguage**s**  (to match what is being returned)

Lots of types are stated with:
 
```
field: {
   [key: string]: any;
}
```

this should be replaced with

`field: Record<string, unknown> `

**Comment by alexpop-zengenti** [comment]
We corrected the EntrySys class in the contensis-management-api 1.0.1 release.
Regarding the _field_ type we will maintain the current definition as it is more suitable for the current use case. If we need to apply more restriction to the key type or name we will look at using the Record class.
